apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: abc
spec:
  container:
    name: storage-initializer
    image: kubeflow/model-files-registry-storage-initializer:latest
    env:
      - name: MODEL_REGISTRY_BASE_URL
        value: "model-registry.rhoai-model-registries.svc.cluster.local:8080"
      - name: MODEL_REGISTRY_SCHEME
        value: "http"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: model-files-registry://
