apiVersion: v1
kind: Pod
metadata:
  name: download-pod
spec:
  containers:
    - name: kserve-container
      image: nvcr.io/nim/meta/llama3-8b-instruct:1.0.3
      env:
        - name: NIM_CACHE_PATH
          value: /tmp
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: nvidia-nim-secrets
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /.cache
          name: cache
  imagePullSecrets:
    - name: ngc-secret
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 16Gi
      name: dshm
    - emptyDir: { }
      name: cache